### ISSUE TITLE
Unable to install signalk-server on raspberry pi zero w (Raspberry Pi OS Lite 32bit)

### ISSUE THREAD

**Issue by vkotov** [SignalK/signalk-server-node#1052]
After executing command `sudo npm install -g --unsafe-perm signalk-server`
some errors happens:
```
> node-gyp rebuild
make: Entering directory '/usr/local/lib/node_modules/signalk-server/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:
../src/mdns.hpp:32:10: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [dns_sd_bindings.target.mk:165: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/signalk-server/node_modules/mdns/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.118+
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/signalk-server/node_modules/mdns
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

```

**Comment by tkurki** [comment]
You need Avahi. https://github.com/SignalK/signalk-server-node/blob/master/Dockerfile#L7

**Comment by sbender9** [comment]
Note that it is an optional dependency, the server will work fine without it.
