### ISSUE TITLE
TypeError: Cannot read property 'notifications' of undefined

### ISSUE THREAD

**Issue by sailoog** [SignalK/signalk-server-node#117]
Raspberry 3
nodejs 6
Master branch downloaded an hour ago.

I'm getting this error:

/home/pi/.config/signalk-server-node/node_modules/signalk-schema/src/fullsignalk.js:175
      if (!previous[pathPart]) {
                   ^

TypeError: Cannot read property 'notifications' of undefined
    at /home/pi/.config/signalk-server-node/node_modules/signalk-schema/src/fullsignalk.js:175:20
    at Array.reduce (native)
    at addValue (/home/pi/.config/signalk-server-node/node_modules/signalk-schema/src/fullsignalk.js:174:43)
    at addValues (/home/pi/.config/signalk-server-node/node_modules/signalk-schema/src/fullsignalk.js:161:5)
    at FullSignalK.addUpdate (/home/pi/.config/signalk-server-node/node_modules/signalk-schema/src/fullsignalk.js:105:3)
    at FullSignalK.addUpdates (/home/pi/.config/signalk-server-node/node_modules/signalk-schema/src/fullsignalk.js:95:10)
    at FullSignalK.addDelta (/home/pi/.config/signalk-server-node/node_modules/signalk-schema/src/fullsignalk.js:52:8)
    at FromJson.<anonymous> (/home/pi/.config/signalk-server-node/lib/pipedproviders.js:47:21)
    at emitOne (events.js:96:13)
    at FromJson.emit (events.js:188:7)
Connection is already closed.

I have some null values in custom notifications keys, is this the problem?

**Comment by sailoog** [comment]
Or have you implemented the alarm system and now notifications paths must point to existing keys?

**Comment by tkurki** [comment]
Can you provide the input delta that causes this?

I am in the middle of implementing alarms, but nothing in master yet.

**Comment by sailoog** [comment]
Not at work now, I think could be caused by another issue with uuid. I will try to report on monday. Thanks.

**Comment by sailoog** [comment]
Fixed.  Wrong uuid/mmsi use in settings file. thanks.
