### ISSUE TITLE
Enabling zones-edit for the first time results in crash

### ISSUE THREAD

**Issue by sbender9** [SignalK/signalk-server-node#118]
```
TypeError: Cannot read property 'reduce' of undefined
    at Object.plugin.start (/usr/local/src/signalk-server-node.master/node_modules/signalk-zones/index.js:81:33)
    at router.post (/usr/local/src/signalk-server-node.master/lib/interfaces/plugins.js:131:14)
    at Layer.handle [as handle_request] (/usr/local/src/signalk-server-node.master/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/src/signalk-server-node.master/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/usr/local/src/signalk-server-node.master/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/src/signalk-server-node.master/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/src/signalk-server-node.master/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/usr/local/src/signalk-server-node.master/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/local/src/signalk-server-node.master/node_modules/express/lib/router/index.js:271:10)
    at /usr/local/src/signalk-server-node.master/node_modules/body-parser/lib/read.js:129:5
_http_outgoing.js:356
    throw new Error('Can\'t set headers after they are sent.');
```

**Comment by sbender9** [comment]
You also have zones-edit and signalk-zones in package.json

**Comment by tkurki** [comment]
I believe this is fixed.
