### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-server-node#125]
After updating master to fd316c66187286c6330fa54ae9e3b5113442b4cb, I get an error on startup:

```
elektron@signalk:~/signalk-server-node$ ./bin/nmea-from-file
/home/elektron/signalk-server-node/lib/interfaces/plugins.js:92
    if (metadata && metadata.keywords && metadata.keywords.includes('signalk-node-server-plugin')) {
                                                           ^

TypeError: metadata.keywords.includes is not a function
    at /home/elektron/signalk-server-node/lib/interfaces/plugins.js:92:60
    at Array.forEach (native)
    at startPlugins (/home/elektron/signalk-server-node/lib/interfaces/plugins.js:85:68)
    at Object.start (/home/elektron/signalk-server-node/lib/interfaces/plugins.js:26:7)
    at /home/elektron/signalk-server-node/lib/index.js:170:30
    at /home/elektron/signalk-server-node/node_modules/lodash/index.js:3073:15
    at Function.forIn (/home/elektron/signalk-server-node/node_modules/lodash/index.js:3362:16)
    at startInterfaces (/home/elektron/signalk-server-node/lib/index.js:162:5)
    at /home/elektron/signalk-server-node/lib/index.js:76:7
    at /home/elektron/signalk-server-node/lib/index.js:100:7
```

**Comment by tkurki** [comment]
What version of Node are you running? It should be 6.

**Comment by ph1l** [comment]
That was it. Thanks!
```
elektron@signalk:~/signalk-server-node$ node --version
v4.6.1
```
