### ISSUE TITLE
Server exits with socket.upgradeReq.headers error after update 

### ISSUE THREAD

**Issue by stevepmitchell** [SignalK/signalk-server-node#204]
Just updated my signalk-server-node install this weekend (I usually update every week) and I am getting an error when entering any browser app - instrumentpanel is the most frequent one that will cause this failure:

`
GET / 200 30.692 ms - 1456
GET /bootstrap/dist/css/bootstrap.min.css 304 12.765 ms - -
GET /jquery/dist/jquery.min.js 304 12.047 ms - -
GET /apps 304 19.406 ms - -
GET /bootstrap/dist/css/bootstrap.min.css 304 4.636 ms - -
GET /jquery/dist/jquery.min.js 304 5.438 ms - -
GET /instrumentpanel/ 304 11.569 ms - -
GET /instrumentpanel/dist/css/bootstrap.min.css 304 93.032 ms - -
GET /instrumentpanel/dist/css/font-awesome.css 304 93.544 ms - -
GET /instrumentpanel/dist/css/settingslist.css 304 94.231 ms - -
GET /instrumentpanel/dist/ui.js 304 93.310 ms - -
GET /instrumentpanel/dist/fonts/fontawesome-webfont.woff2?v=4.4.0 304 1.795 ms - -
/home/pi/signalk-server-node/node_modules/primus/transformers/websockets/server.js:37
          socket.upgradeReq.headers               // HTTP request headers.
                           ^

TypeError: Cannot read property 'headers' of undefined
    at service.handleUpgrade (/home/pi/signalk-server-node/node_modules/primus/transformers/websockets/server.js:37:28)
    at WebSocketServer.completeUpgrade (/home/pi/signalk-server-node/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/home/pi/signalk-server-node/node_modules/ws/lib/WebSocketServer.js:197:10)
    at child.on (/home/pi/signalk-server-node/node_modules/primus/transformers/websockets/server.js:35:18)
    at child.emit (/home/pi/signalk-server-node/node_modules/eventemitter3/index.js:131:35)
    at emitter (/home/pi/signalk-server-node/node_modules/emits/index.js:26:22)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:125:24)
    at done (/home/pi/signalk-server-node/node_modules/primus/transformer.js:139:7)
    at Primus.client (/home/pi/signalk-server-node/node_modules/primus/middleware/authorization.js:19:49)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:136:14)`

**Comment by sbender9** [comment]
I just tested with the latest and I don't see this issue. What browser are you using?

**Comment by tkurki** [comment]
Did you wipe node_modules and reinstall deps or just git pull?

**Comment by stevepmitchell** [comment]
I've tried Chrome and Safari @sbender9. I did not wipe node_modules. Will try that now. Is that a new install process?

**Comment by stevepmitchell** [comment]
Ah much better, it's at least running now after purging node_modules. I will give it some more testing.
