### ISSUE TITLE
(Possible) memory leak in the N2K provider

### ISSUE THREAD

**Issue by fabdrol** [SignalK/signalk-server-node#24]
@tkurki: when running the n2k config for a while, I get a memory leak. Have you experienced this as well?

```
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EndIgnoringPassThrough.addListener (events.js:160:15)
    at EndIgnoringPassThrough.Readable.on (_stream_readable.js:707:33)
    at EndIgnoringPassThrough.once (events.js:185:8)
    at ReadStream.Readable.pipe (_stream_readable.js:559:8)
    at FileStream.startStream (/Users/Fabian/Dropbox/Sites/SignalK/signalk-server-node/providers/filestream.js:46:21)
    at ReadStream.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by tkurki** [comment]
I've seen this also, but 
* I think it is related to FileStream in general, not n2k
* heapdumps from a running instance do not show increase

**Comment by fabdrol** [comment]
Hm, in that case it might just be leaking event listeners. Shouldn't be too hard to track down. I'll take a look at it

**Comment by tkurki** [comment]
Not an issue, just log messages.
