### ISSUE TITLE
CRASH: All files in mapcache treated as mbtiles

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#252]
OSX creates files such as mapcache.DS_Store and mapcache.gitignore in the public folder when starting the server. These are currently treated as mbtiles by the server, and the server crashes again with this message: 
```/Users/joachim/Downloads/signalk-server-node/lib/interfaces/charts.js:157
        if (_.isUndefined(mbtilesData.name)) {
                                     ^

TypeError: Cannot read property 'name' of undefined
    at mbtiles.getInfo (/Users/joachim/Downloads/signalk-server-node/lib/interfaces/charts.js:157:38)
    at /Users/joachim/Downloads/signalk-server-node/node_modules/@mapbox/mbtiles/lib/mbtiles.js:232:44
    at Statement.errBack (/Users/joachim/Downloads/signalk-server-node/node_modules/sqlite3/lib/sqlite3.js:16:21)```

**Comment by joabakk** [comment]
The error came with add4e55
