### ISSUE TITLE
A broken npm install may keep server from starting

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#268]
A hung plugin npm install & forced restart left my server in a state where it will not start:
```
Aug  7 06:25:13 cassiopeia signalk-server[10417]: { Error: Cannot find module '.././node_modules/.staging/package.json'
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at Function.Module._resolveFilename (module.js:470:15)
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at Function.Module._load (module.js:418:25)
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at Module.require (module.js:498:17)
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at require (internal/module.js:20:19)
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at fs.readdirSync.filter.reduce (/opt/signalk-server/lib/modules.js:43:22)
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at Array.reduce (native)
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at findModulesInDir (/opt/signalk-server/lib/modules.js:30:6)
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at modulesWithKeyword (/opt/signalk-server/lib/modules.js:23:10)
Aug  7 06:25:13 cassiopeia signalk-server[10417]: at startPlugins (/opt/signalk-server/lib/interfaces/plugins.js:99:3)
```

**Comment by tkurki** [comment]
Apparently not  a real issue.
