### ISSUE TITLE
WS error

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#274]
While testing https://github.com/tkurki/pebble-signalk I get: 
```/home/pi/signalk-server-node/node_modules/primus/transformers/websockets/server.js:37
          socket.upgradeReq.headers               // HTTP request headers.
                           ^

TypeError: Cannot read property 'headers' of undefined
    at service.handleUpgrade (/home/pi/signalk-server-node/node_modules/primus/transformers/websockets/server.js:37:28)
    at WebSocketServer.completeUpgrade (/home/pi/signalk-server-node/node_modules/ws/lib/WebSocketServer.js:270:5)
    at WebSocketServer.handleUpgrade (/home/pi/signalk-server-node/node_modules/ws/lib/WebSocketServer.js:197:10)
    at child.on (/home/pi/signalk-server-node/node_modules/primus/transformers/websockets/server.js:35:18)
    at child.emit (/home/pi/signalk-server-node/node_modules/eventemitter3/index.js:131:35)
    at emitter (/home/pi/signalk-server-node/node_modules/emits/index.js:26:22)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:125:24)
    at done (/home/pi/signalk-server-node/node_modules/primus/transformer.js:139:7)
    at Primus.client (/home/pi/signalk-server-node/node_modules/primus/middleware/authorization.js:19:49)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:136:14)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:126:60)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:126:60)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:126:60)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:126:60)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:126:60)
    at iterate (/home/pi/signalk-server-node/node_modules/primus/transformer.js:132:14)```

**Comment by joabakk** [comment]
ah, duplicate of #204
