### ISSUE TITLE
Exception when setting design.shipType

### ISSUE THREAD

**Issue by sbender9** [SignalK/signalk-server-node#296]
While testing this I'm getting the following exception.

```
TypeError: Cannot create property 'value' on number '36'
    at assignValueToLeaf (/usr/local/src/signalk-server-node.include-metadata/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:241:16)
    at addValue (/usr/local/src/signalk-server-node.include-metadata/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:225:3)
    at addValues (/usr/local/src/signalk-server-node.include-metadata/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:174:5)
    at FullSignalK.addUpdate (/usr/local/src/signalk-server-node.include-metadata/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:108:3)
    at FullSignalK.addUpdates (/usr/local/src/signalk-server-node.include-metadata/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:96:10)
    at FullSignalK.addDelta (/usr/local/src/signalk-server-node.include-metadata/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:53:8)
    at EventEmitter.Server.app.handleMessage (/usr/local/src/signalk-server-node.include-metadata/lib/index.js:128:19)
    at DeMultiplexer.result.pipeElements.(anonymous function).on.msg (/usr/local/src/signalk-server-node.include-metadata/lib/pipedproviders.js:44:11)
    at emitOne (events.js:96:13)
    at DeMultiplexer.emit (events.js:188:7)
    at ToSignalK.Splitter.demuxEmitData (/usr/local/src/signalk-server-node.include-metadata/providers/multiplexedlog.js:67:19)
    at emitOne (events.js:101:20)
    at ToSignalK.emit (events.js:188:7)
```

This is when design.aisShipType is getting set to 36

I've never seen this before, so it must from a recent change.

**Comment by tkurki** [comment]
Do you have the delta producing this?

**Comment by sbender9** [comment]
It's coming from one of my log files that I've been using for a long time. I have to let it run for a while before this happens. Any ideas on how I can narrow it down and capture the delta?

**Comment by tkurki** [comment]
Try catch around Demultiplexer emit call for example.

**Comment by sbender9** [comment]
```
{"updates":[{"source":{
"label":"n2kFromFile","type":"NMEA2000","pgn":129810,"src":"43"},"timestamp":"20
17-04-15T15:01:01.945Z","values":[{"path":"design.length","value":{"overall":9}}
,{"path":"design.aisShipType","value":36},{"path":"design.beam","value":4},{"pat
h":"sensors.ais.fromBow","value":6},{"path":"sensors.ais.fromCenter","value":0}]
}],"context":"vessels.urn:mrn:imo:mmsi:338184312"}
```

**Comment by tkurki** [comment]
Can't repro with a fresh install of server off Github. Could be an interaction with a previous message. Can you reproduce with a clean server?

**Comment by sbender9** [comment]
I’m using the include-meta branch. I will try again with a fresh install...

**Comment by sbender9** [comment]
Shoot. Sorry, I forgot I had also installed signalk-schema 0.0.1-8.

**Comment by sbender9** [comment]
I was able to reproduce with a fresh include-metadata branch without updating signalk-schema

**Comment by tkurki** [comment]
Not related to include-metadata, but specific detault setup.
