### ISSUE TITLE
More robust server 

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-server-node#30]
A single misbehaving producer can stop the whole server. The error reported in https://github.com/SignalK/signalk-parser-nmea0183/issues/22 stops the server.

```
TypeError: Cannot call method 'toUpperCase' of undefined
    at NMEA0183.magneticVariaton (/Users/tkurki/git-workspace/signalk/server-node/node_modules/nmea0183-signalk/lib/NMEA0183.js:116:15)
    at null._decoder (/Users/tkurki/git-workspace/signalk/server-node/node_modules/nmea0183-signalk/codecs/RMC.js:86:48)
    at NMEA0183.decode (/Users/tkurki/git-workspace/signalk/server-node/node_modules/nmea0183-signalk/lib/NMEA0183.js:220:24)
    at Parser._decode (/Users/tkurki/git-workspace/signalk/server-node/node_modules/nmea0183-signalk/lib/index.js:91:44)
    at /Users/tkurki/git-workspace/signalk/server-node/node_modules/nmea0183-signalk/lib/index.js:134:22
    at Function.forEach (/Users/tkurki/git-workspace/signalk/server-node/node_modules/lodash/dist/lodash.js:3297:15)
    at Parser._transform (/Users/tkurki/git-workspace/signalk/server-node/node_modules/nmea0183-signalk/lib/index.js:131:5)
    at Parser.Transform._read (_stream_transform.js:179:10)
    at Parser.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:226:10)
```

**Comment by tkurki** [comment]
Example: unhandled multiline ais messages stop the server

**Comment by fabdrol** [comment]
I ran into this issue during my trip to England last week and started/continued work on a solution. I'll post my initial (experimental) work in a branch.
