### ISSUE TITLE
kplex crashes signalk-server-node

### ISSUE THREAD

**Issue by e-sailing** [SignalK/signalk-server-node#334]
When starting kplex or when kplex is started signalk-server-node crashes with error message:

`pi@openplotter:~/.config/signalk-server-node $ bin/signalk-server -s ../../.openplotter/openplotter-settings.json
No settings/defaults.json available
{ APB:
   { title: 'APB - Autopilot info',
     keys:
      [ 'navigation.courseGreatCircle.crossTrackError',
        'navigation.courseGreatCircle.bearingTrackTrue',
        'navigation.courseGreatCircle.nextPoint' ],
     f: [Function: f] },
...
...
  ZDA:
   { title: 'ZDA - UTC time and date',
     keys: [ 'navigation.datetime' ],
     f: [Function: f] } }
signalk-server running at 0.0.0.0:3000

Error reading /home/pi/.config/signalk-server-node/public/mapcache
buffer.js:479
          throw new TypeError('Unknown encoding: ' + encoding);
          ^

TypeError: Unknown encoding: buffer
    at Buffer.slowToString (buffer.js:479:17)
    at Buffer.toString (buffer.js:492:27)
    at nmea0183ToSignalK._transform (/home/pi/.config/signalk-server-node/providers/nmea0183-signalk.js:80:19)
    at nmea0183ToSignalK.Transform._read (_stream_transform.js:167:10)
    at nmea0183ToSignalK.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at nmea0183ToSignalK.Writable.write (_stream_writable.js:245:11)
    at Udp.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Udp.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Udp.Readable.push (_stream_readable.js:134:10)
    at Udp.Transform.push (_stream_transform.js:128:32)
    at Socket.<anonymous> (/home/pi/.config/signalk-server-node/providers/udp.js:55:10)
    at emitTwo (events.js:106:13)
`
kplex sends on udp 55556
This only happens with a new installed signalk!
Older versions doesn't have this error.
(One week ago everything works fine.

**Comment by tkurki** [comment]
Fixed by #335. 

Not related to kplex, just a bug in the new nmea0183 parser's integration code that crashed with any udp input.
