### ISSUE TITLE
admin-ui install failure on raspberry pi: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 8.x

### ISSUE THREAD

**Issue by ph1l** [SignalK/signalk-server-node#480]
> pi@marinepi:/opt/signalk-server/admin-ui $ (npm run clean && npm run build) 2>&1 | tee /tmp/failure.log

```
ERROR in ./node_modules/css-loader?{"alias":{"../img":"../public_src/img"}}!./node_modules/sass-loader/lib/loader.js!./scss/style.scss
Module build failed: Error: Node Sass does not yet support your current environment: Linux Unsupported architecture (arm) with Node.js 8.x
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.7.1
    at module.exports (/opt/signalk-server/admin-ui/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/opt/signalk-server/admin-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/signalk-server/admin-ui/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLoader (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/opt/signalk-server/admin-ui/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/opt/signalk-server/admin-ui/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/opt/signalk-server/admin-ui/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/opt/signalk-server/admin-ui/node_modules/webpack/lib/Compilation.js:151:10)
    at factoryCallback (/opt/signalk-server/admin-ui/node_modules/webpack/lib/Compilation.js:344:12)
    at factory (/opt/signalk-server/admin-ui/node_modules/webpack/lib/NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (/opt/signalk-server/admin-ui/node_modules/webpack/lib/NormalModuleFactory.js:94:13)
 @ ./scss/style.scss 4:14-127 18:2-22:4 19:20-133
 @ ./src/index.js
 @ multi ./src/index.js
```
full log: [failure.log](https://github.com/SignalK/signalk-server-node/files/1820338/failure.log)

**Comment by sbender9** [comment]
Yes. Currently you have to build the admin-UI elsewhere. 

Alternatively, you can do the npm global install (see the README for instructions).

**Comment by ph1l** [comment]
okay, then I suppose i should also file this bug in https://github.com/tkurki/marinepi-provisioning

**Comment by ph1l** [comment]
when you say build the admin-ui elsewhere, what does that mean? what are the build objects that I would need to copy?

**Comment by sbender9** [comment]
On a machine that Sass is supported on, do `npm run prebuildOnly`

Then copy `admin-ui/public/*` and `plugin-config/public/*`

**Comment by ph1l** [comment]
Thanks, this seems to work around:

```
rsync -av admin-ui/public/* pi@marinepi:/opt/signalk-server/admin-ui/public/
rsync -av plugin-config/public/* pi@marinepi:/opt/signalk-server/admin-ui/public/
```

**Comment by tkurki** [comment]
Add this to developer instructions? Somebody recently built or tried to build the ui's on a Pi zero - probably never got this far, ended up waiting quite a while...

**Comment by tkurki** [comment]
c8905c9a8e33794de32fc9a484229eb49282e8c0
