### ISSUE TITLE
Signal K Server crash in production

### ISSUE THREAD

**Issue by Krillle** [SignalK/signalk-server-node#668]
After uptime for several months my Signal K Server crashed with the following. After rebooting Raspberry Pi it was working well again:

```Nov 19 14:36:21 signalk systemd[1]: Started signalk.service.
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.413Z signalk-server Starting server to serve only http
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.420Z signalk-server ID type: mmsi
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.421Z signalk-server ID: urn:mrn:imo:mmsi:211598410
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.422Z signalk-server Interfaces config:{}
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.572Z signalk-server Loading interface 'admin-ui'
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.573Z signalk-server Starting interface 'admin-ui'
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.575Z signalk-server Loading interface 'appstore'
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.578Z signalk-server Starting interface 'appstore'
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.581Z signalk-server Loading interface 'nmea-tcp'
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.583Z signalk-server Starting interface 'nmea-tcp'
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.594Z signalk-server Loading interface 'plugins'
Nov 19 14:36:22 signalk signalk-server[23552]: 2018-11-19T14:36:22.597Z signalk-server Starting interface 'plugins'
Nov 19 14:36:22 signalk signalk-server[23552]: SyntaxError: /usr/lib/node_modules/signalk-server/node_modules/colorspace/package.json: Unexpected token * in JSON at position 1
Nov 19 14:36:22 signalk signalk-server[23552]:     at JSON.parse (<anonymous>)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Object.Module._extensions..json (module.js:671:27)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Module.load (module.js:565:32)
Nov 19 14:36:22 signalk signalk-server[23552]:     at tryModuleLoad (module.js:505:12)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Function.Module._load (module.js:497:3)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Module.require (module.js:596:17)
Nov 19 14:36:22 signalk signalk-server[23552]:     at require (internal/module.js:11:18)
Nov 19 14:36:22 signalk signalk-server[23552]:     at fs.readdirSync.filter.reduce (/usr/lib/node_modules/signalk-server/lib/modules.js:70:22)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Array.reduce (<anonymous>)
Nov 19 14:36:22 signalk signalk-server[23552]:     at findModulesInDir (/usr/lib/node_modules/signalk-server/lib/modules.js:56:6)
Nov 19 14:36:22 signalk signalk-server[23552]: SyntaxError: /usr/lib/node_modules/signalk-server/node_modules/commander/package.json: Unexpected token
Nov 19 14:36:22 signalk signalk-server[23552]:     at JSON.parse (<anonymous>)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Object.Module._extensions..json (module.js:671:27)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Module.load (module.js:565:32)
Nov 19 14:36:22 signalk signalk-server[23552]:     at tryModuleLoad (module.js:505:12)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Function.Module._load (module.js:497:3)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Module.require (module.js:596:17)
Nov 19 14:36:22 signalk signalk-server[23552]:     at require (internal/module.js:11:18)
Nov 19 14:36:22 signalk signalk-server[23552]:     at fs.readdirSync.filter.reduce (/usr/lib/node_modules/signalk-server/lib/modules.js:70:22)
Nov 19 14:36:22 signalk signalk-server[23552]:     at Array.reduce (<anonymous>)
Nov 19 14:36:22 signalk signalk-server[23552]:     at findModulesInDir (/usr/lib/node_modules/signalk-server/lib/modules.js:56:6)
Nov 19 14:36:23 signalk signalk-server[23552]: 2018-11-19T14:36:23.361Z signalk-server Loading interface 'providers'
Nov 19 14:36:23 signalk signalk-server[23552]: 2018-11-19T14:36:23.365Z signalk-server Loading interface 'rest'
Nov 19 14:36:23 signalk signalk-server[23552]: 2018-11-19T14:36:23.366Z signalk-server Starting interface 'rest'
Nov 19 14:36:23 signalk signalk-server[23552]: 2018-11-19T14:36:23.368Z signalk-server Loading interface 'tcp'
Nov 19 14:36:23 signalk signalk-server[23552]: 2018-11-19T14:36:23.369Z signalk-server Starting interface 'tcp'
Nov 19 14:36:23 signalk signalk-server[23552]: 2018-11-19T14:36:23.372Z signalk-server Loading interface 'webapps'
Nov 19 14:36:23 signalk signalk-server[23552]: 2018-11-19T14:36:23.372Z signalk-server Starting interface 'webapps'
Nov 19 14:36:23 signalk signalk-server[23552]: SyntaxError: /usr/lib/node_modules/signalk-server/node_modules/colorspace/package.json: Unexpected token * in JSON at position 1
Nov 19 14:36:23 signalk signalk-server[23552]:     at JSON.parse (<anonymous>)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Object.Module._extensions..json (module.js:671:27)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Module.load (module.js:565:32)
Nov 19 14:36:23 signalk signalk-server[23552]:     at tryModuleLoad (module.js:505:12)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Function.Module._load (module.js:497:3)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Module.require (module.js:596:17)
Nov 19 14:36:23 signalk signalk-server[23552]:     at require (internal/module.js:11:18)
Nov 19 14:36:23 signalk signalk-server[23552]:     at fs.readdirSync.filter.reduce (/usr/lib/node_modules/signalk-server/lib/modules.js:70:22)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Array.reduce (<anonymous>)
Nov 19 14:36:23 signalk signalk-server[23552]:     at findModulesInDir (/usr/lib/node_modules/signalk-server/lib/modules.js:56:6)
Nov 19 14:36:23 signalk signalk-server[23552]: SyntaxError: /usr/lib/node_modules/signalk-server/node_modules/commander/package.json: Unexpected token
Nov 19 14:36:23 signalk signalk-server[23552]:     at JSON.parse (<anonymous>)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Object.Module._extensions..json (module.js:671:27)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Module.load (module.js:565:32)
Nov 19 14:36:23 signalk signalk-server[23552]:     at tryModuleLoad (module.js:505:12)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Function.Module._load (module.js:497:3)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Module.require (module.js:596:17)
Nov 19 14:36:23 signalk signalk-server[23552]:     at require (internal/module.js:11:18)
Nov 19 14:36:23 signalk signalk-server[23552]:     at fs.readdirSync.filter.reduce (/usr/lib/node_modules/signalk-server/lib/modules.js:70:22)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Array.reduce (<anonymous>)
Nov 19 14:36:23 signalk signalk-server[23552]:     at findModulesInDir (/usr/lib/node_modules/signalk-server/lib/modules.js:56:6)
Nov 19 14:36:23 signalk signalk-server[23552]: 2018-11-19T14:36:23.394Z signalk-server Loading interface 'ws'
Nov 19 14:36:23 signalk signalk-server[23552]: { SyntaxError: Error parsing /usr/lib/node_modules/signalk-server/node_modules/colorspace/package.json: Unexpected token * in JSON at position 1
Nov 19 14:36:23 signalk signalk-server[23552]:     at JSON.parse (<anonymous>)
Nov 19 14:36:23 signalk signalk-server[23552]:     at readPackage (module.js:126:52)
Nov 19 14:36:23 signalk signalk-server[23552]:     at tryPackage (module.js:136:13)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Function.Module._findPath (module.js:218:20)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Function.Module._resolveFilename (module.js:545:25)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Function.Module._load (module.js:474:25)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Module.require (module.js:596:17)
Nov 19 14:36:23 signalk signalk-server[23552]:     at require (internal/module.js:11:18)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Object.<anonymous> (/usr/lib/node_modules/signalk-server/node_modules/diagnostics/index.js:3:18)
Nov 19 14:36:23 signalk signalk-server[23552]:     at Module._compile (module.js:652:30)
Nov 19 14:36:23 signalk signalk-server[23552]:   path: '/usr/lib/node_modules/signalk-server/node_modules/colorspace/package.json' }
Nov 19 14:36:23 signalk systemd[1]: signalk.service: Main process exited, code=exited, status=255/n/a
Nov 19 14:36:23 signalk systemd[1]: signalk.service: Unit entered failed state.
Nov 19 14:36:23 signalk systemd[1]: signalk.service: Failed with result 'exit-code'.```

**Comment by tkurki** [comment]
Your log shows a restart and you talk about uptime of several months - what caused the restart?

Have you checked the contents of the offending package.json files?

**Comment by Krillle** [comment]
Signal K was was running as a service (autostart option in signalk-server-setup) and restarted every 10 seconds after crash. I copied just the last crash in log.

**Comment by Krillle** [comment]
> Have you checked the contents of the offending package.json files?

No. As after restart is worked again I was not eager enough. It's 4° on the boat.

**Comment by tkurki** [comment]
Do you have log snippet  for the first real crash? Anything else of note in the log, anything indicating sd card issues?

**Comment by Krillle** [comment]
>Do you have log snippet for the first real crash? 
I will check tomorrow. It was starting and crashing for a week. Not sure if this will be still in the log history.

>Anything else of note in the log, anything indicating sd card issues?
After restart system indeed needed a power cycle to find Wifi again. Now Signal K is running but not communicating with NMEA. Was thinking a SD card issue too. Will have a closer look on that.

Nevertheless: Signal K is running now without problems.

**Comment by Krillle** [comment]
> Do you have log snippet for the first real crash?

Unfortunately what I get with `journalctl -u signalk > signalk-error.log` starts with the reboot after the crash. Is there a way to get the old logs?

**Comment by Krillle** [comment]
This is the contents of file `/usr/lib/node_modules/signalk-server/node_modules/colorspace/package.json`:

```{
  "_from": "colorspace@1.0.x",
  "_id": "colorspace@1.0.1",
  "_inBundle": false,
  "_integrity": "sha1-yZx5btMRKLmHalLh7l7gOkpxl0k=",
  "_location": "/signalk-server/colorspace",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "colorspace@1.0.x",
    "name": "colorspace",
    "escapedName": "colorspace",
    "rawSpec": "1.0.x",
    "saveSpec": null,
    "fetchSpec": "1.0.x"
  },
  "_requiredBy": [
    "/signalk-server/diagnostics"
  ],
  "_resolved": "https://registry.npmjs.org/colorspace/-/colorspace-1.0.1.tgz",
  "_shasum": "c99c796ed31128b9876a52e1ee5ee03a4a719749",
  "_spec": "colorspace@1.0.x",
  "_where": "/usr/lib/node_modules/signalk-server/node_modules/diagnostics",
  "author": {
    "name": "Arnout Kazemier"
  },
  "bundleDependencies": false,
  "dependencies": {
    "color": "0.8.x",
    "text-hex": "0.0.x"
  },
  "deprecated": false,
  "description": "Generate HEX colors for a given namespace.",
  "devDependencies": {
    "assume": "1.2.x",
    "mocha": "2.2.x",
    "pre-commit": "1.0.x"
  },
  "keywords": [
    "namespace",
    "color",
    "hex",
    "colorize",
    "name",
    "space",
    "colorspace"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "colorspace",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "1.0.1"
}
```

**Comment by Krillle** [comment]
This is the contents of the second file with error `/usr/lib/node_modules/signalk-server/node_modules/commander/package.json`:

```
{
  "_from": "commander@^2.7.1",
  "_id": "commander@2.15.1",
  "_inBundle": false,
  "_integrity": "sha512-VlfT9F3V0v+jr4yxPc5gg9s62/fIVWsd2Bk2iD435um1NlGMYdVCq+MjcXnhYq2icNOizHr1kK+5TI6H0Hy0ag==",
  "_location": "/signalk-server/commander",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "commander@^2.7.1",
    "name": "commander",
    "escapedName": "commander",
    "rawSpec": "^2.7.1",
    "saveSpec": null,
    "fetchSpec": "^2.7.1"
  },
  "_requiredBy": [
    "/signalk-server/serialport",
    "/signalk-server/stream-throttle",
    "/signalk-server/z-schema"
  ],
  "_resolved": "https://registry.npmjs.org/commander/-/commander-2.15.1.tgz",
  "_shasum": "df46e867d0fc2aec66a34662b406a9ccafff5b0f",
  "_spec": "commander@^2.7.1",
  "_where": "/usr/lib/node_modules/signalk-server/node_modules/z-schema",
  "author": {
    "name": "TJ Holowaychuk",
    "email": "tj@vision-media.ca"
  },
  "bugs": {
    "url": "https://github.com/tj/commander.js/issues"
  },
  "bundleDependencies": false,
  "dependencies": {},
  "deprecated": false,
  "description": "the complete solution for node.js command-line programs",
  "devDependencies": {
    "@types/node": "^7.0.55",
    "eslint": "^3.19.0",
    "should": "^11.2.1",
    "sinon": "^2.4.1",
    "standard": "^10.0.3",
    "typescript": "^2.7.2"
  },
  "files": [
    "index.js",
    "typings/index.d.ts"
  ],
  "homepage": "https://github.com/tj/commander.js#readme",
  "keywords": [
    "commander",
    "command",
    "option",
    "parser"
  ],
  "license": "MIT",
  "main": "index",
  "name": "commander",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/tj/commander.js.git"
  },
  "scripts": {
    "lint": "eslint index.js",
    "test": "make test && npm run test-typings",
    "test-typings": "node_modules/typescript/bin/tsc -p tsconfig.json"
  },
  "typings": "typings/index.d.ts",
  "version": "2.15.1"
}
```

**Comment by Krillle** [comment]
I meanwhile assume it was a SD card glitch. Websockets are bot working correctly either. 
I will reinstall the system.
