### ISSUE TITLE
Using all cpus of multi-core computers

### ISSUE THREAD

**Issue by joabakk** [SignalK/signalk-server-node#672]
How much work would it be to fork the processes to multiple cpus if available. Looking at the examples like http://www.acuriousanimal.com/2017/08/12/understanding-the-nodejs-cluster-module.html, they are quite simple servers. Does anyone have any experience in this?

**Comment by joabakk** [comment]
OK I have created a branch at https://github.com/joabakk/signalk-server-node/tree/multicore. I get a sound debug and the server is working: 
```signalk-server Master cluster setting up 4 workers... +0ms
  signalk-server Worker 28798 is online +215ms
  signalk-server Worker 28799 is online +8ms
  signalk-server Worker 28801 is online +66ms
  signalk-server Worker 28800 is online +14ms
  signalk-server Starting server to serve only http +0ms
  signalk-server ID type: mmsi +5ms
  signalk-server Starting server to serve only http +0ms
  signalk-server ID: urn:mrn:imo:mmsi:1000000 +10ms
  signalk-server Interfaces config:{"appstore":true,"nmea-tcp":true,"plugins":true,"providers":true,"rest":t
rue,"tcp":true,"webapps":true,"ws":true} +1ms
  signalk-server ID type: mmsi +4ms```

The exceptions are a few warnings: 
```  signalk-server Starting interface 'plugins' +6ms
/Users/joachim/Downloads/signalk-server-node/lib/deltastats.js:33
          wsClients: app.interfaces['ws']
                                   ^

TypeError: Cannot read property 'ws' of undefined
    at Timeout.setInterval [as _onTimeout] (/Users/joachim/Downloads/signalk-server-node/lib/deltastats.js:3
3:36)
    at ontimeout (timers.js:460:11)
    at tryOnTimeout (timers.js:298:5)
    at Timer.listOnTimeout (timers.js:261:5)```
 and a few of these: 
```signalk-server Starting interface 'ws' +154ms
Primus:
Primus: The `cluster` module does not implement sticky sessions. Learn more about
Primus: this issue at:
Primus:
Primus: http://github.com/primus/primus#can-i-use-cluster
Primus:
  signalk-server Starting interface 'mDNS' +45ms```

**Comment by joabakk** [comment]
Thanks, yes I was only playing. At closer look it did not work and it looked to be too easy.

**Comment by tkurki** [comment]
Reopen when needed.
