### ISSUE TITLE
Issues with playback of Signal K log data when plugins are included

### ISSUE THREAD

**Issue by cannonerd** [SignalK/signalk-server-node#947]
Here we hit a problem on a log entry with a ruuvitag:

```
TypeError: Cannot create property 'label' on string 'ruuvitag.f681c4'
    at /home/ihmis-suski/projects/meri-imperiumi/signalk-server-node/lib/index.js:137:41
    at Array.forEach (<anonymous>)
    at Function.Server.app.handleMessage (/home/ihmis-suski/projects/meri-imperiumi/signalk-server-node/lib/index.js:135:26)
    at Simple.result.pipeElements.(anonymous function).on.msg (/home/ihmis-suski/projects/meri-imperiumi/signalk-server-node/lib/pipedproviders.js:36:17)
    at Simple.emit (events.js:185:15)
    at Simple.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Simple.Readable.push (_stream_readable.js:218:10)
    at Simple.Transform.push (_stream_transform.js:146:32)
    at Simple._transform (/home/ihmis-suski/projects/meri-imperiumi/signalk-server-node/node_modules/@signalk/streams/simple.js:79:8)
    at Simple.Transform._read (_stream_transform.js:185:10)
    at Simple.Transform._write (_stream_transform.js:173:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:396:5)
    at Simple.Writable.write (_stream_writable.js:294:11)
```

This is with https://github.com/meri-imperiumi/signalk-autostate/blob/master/test/logs/skserver-raw_2019-09-21T12.log

**Comment by tkurki** [comment]
`1569067200571;ruuvitag;{"updates":[{"source":"ruuvitag.f681c4"....``

`source` should be an object per SK schema.

 The server does almost no validation on the data, so this works in real life but not from a file apparently.

Try search and replacing `source` with `$source`, that should work.

**Comment by cannonerd** [comment]
Thanks! 
Will try replacing and will file bug in the RuuviTag plugin.
